pipeline:
  docker-explode-acme-json:
    when:
      status: [success, failure, changed]
    image: plugins/docker:1.12
    repo: registry.eorlbruder.de/explode-acme-json
    registry: registry.eorlbruder.de
    tags:
      - latest
    dockerfile: ./explode-acme-json/Dockerfile
    context: ./explode-acme-json
    secrets: [docker_username, docker_password]
  notify:
    image: drillster/drone-email
    when:
      branch: master
      status: [success, failure, changed]
    secrets:
      - source: email_host
        target: email_host
      - source: email_password
        target: email_password
      - source: email
        target: plugin_from
      - source: email
        target: email_username
      - source: email
        target: email_recipients
